### ISSUE TITLE
Research a better versioning system

### ISSUE THREAD

**Issue by LowPowerLab** [LowPowerLab/RaspberryPi-Gateway#27]
Ideally should give a visual overview of the software version along with all dependencies versions.

**Comment by karrots** [comment]
http://semver.org/

**Comment by LowPowerLab** [comment]
Great,
I think for the scope of this project it will get pretty tedious to keep track of a patch in addition the the minor. Not without an automatic way of semver-ing.

**Comment by karrots** [comment]
There are grunt scripts you can do a version bump on the package.json file then commits the changes to git and apply a new tag with the version number as well. Some can then cause a new [Github release to happen via the API](https://help.github.com/articles/creating-releases/). Even with that automation, is still going to take a human to determine if it's a patch or a feature release. This also would require more granular commits (not necessarily pushes though). 

Remember every commit doesn't equal a need to advance the version number, but every public release to the master branch probably should. The dev branch could have a bunch of patches and small features pushed to it over multiple commits. Then a merge from dev to master happens and the version number is incremented in some fashion. Or all development happens in master and the version number is incremented periodically based on the traffic. I would probably only do development in master if people generally downloaded ZIP or tarballs from the releases section rather than cloning the repository.

Examples:

https://www.npmjs.com/package/grunt-bumpup
https://github.com/kswedberg/grunt-version
https://github.com/vojtajina/grunt-bump
http://gruntjs.com/plugins/bump
https://docs.npmjs.com/cli/version

**Comment by cacack** [comment]
Semantic versioning is a great methodology to follow as it fairly universal.  So without understanding the exact changes between release, as a consumer, I can quickly gauge the scope of a release...

For example,
- 1.3.2 --> 1.3.4 == minor bug fixes so I can upgrade without giving much thought
- 1.2.1 --> 1.3 == I probably need to read a changelog to see what new features there are
- 1.5 --> 2.0 == big changes and likely not compatible so **must** read changelog

**Comment by cacack** [comment]
And I don't think semantic versioning requires the use of bug/patch version number.  It really just puts some definitions around what it means to be a major, minor, and bug/patch version number.  So you can continue to go 8.3 --> 8.4 --> 8.5, but I would take that to mean there are new features being added and likely bugs fixes too.

**Comment by LowPowerLab** [comment]
Using npm standard package.json version formatting, which is now shown in the UI under MENU.
