### ISSUE TITLE
Install script improvements

### ISSUE THREAD

**Issue by Mike6gPerso** [LowPowerLab/RaspberryPi-Gateway#29]
Install script is a great starting point, however I guess it is not complete

Running with Rpi 2 (Jessie), the UART is disabled by default on Jessie
see: https://hallard.me/enable-serial-port-on-raspberry-pi/
> I also noticed sometimes UART is disabled in kernel. The enable it you need to check in /boot/config.txt the line enable_uart

Also, starting from line 76, the node folder is incorrect and should be redefined as 
> NODEDIR=$NODEDIR/node-v4.6.2-linux-armv6l
Otherwise the node is not really in the path 

One more thing, the default baud speed for the gateway is:
> #define SERIAL_BAUD 115200
whereas in the settings.json5 in this repo it defines 19200

Keep up the awesome work !!

**Comment by LowPowerLab** [comment]
Thanks for the comments,

**RE serial** - looks like setup it's different for various releases. Not 100% convinced this really belongs in the app setup script (although could be nice as an optional subroutine) but maybe a separate setup script that deals with the serial on Pi2/Pi3 could be invoken optionally by the gateway setup script (if one exists or someone will ever make one). If I ever get time I may look into making that script myself.

**RE node** this is not a problem, the mv moves that content to /opt/node/bin:
`pi@raspberrypi2B:/usr/local/bin $ cd ~
pi@raspberrypi2B:~ $ cd /opt/node/bin
pi@raspberrypi2B:/opt/node/bin $ ls -la | grep node
-rwxrwxr-x 1 1001 1001 22238431 Nov  8 17:31 node
lrwxrwxrwx 1 1001 1001       38 Nov  8 17:32 npm -> ../lib/node_modules/npm/bin/npm-cli.js
pi@raspberrypi2B:/opt/node/bin $ which node
/usr/local/bin/node
pi@raspberrypi2B:/opt/node/bin $ cd /usr/local/bin
pi@raspberrypi2B:/usr/local/bin $ ls -la | grep node
lrwxrwxrwx  1 root staff   18 Nov 11 21:41 node -> /opt/node/bin/node
lrwxrwxrwx  1 root staff   17 Nov 11 21:41 npm -> /opt/node/bin/npm
`

**RE baud speed** - not sure where you see 115200. The examples to use with the Pi are [here](https://github.com/LowPowerLab/RFM69/tree/master/Examples/PiGateway) and [here](https://github.com/LowPowerLab/RFM69/blob/master/Examples/MightyHat/MightyHat.ino), both are 19200.

Since there is no bug per se I will close this issue, thanks again.

**Comment by Mike6gPerso** [comment]
Ok thanks for your feedback

Serial --> I agree, it was more like an information, maybe the script can check the UART status

Node --> Not sure I explained myself properly
but I think if you do:
> sudo mv node-v4.6.2-linux-armv6l $NODEDIR
the new folder created is /opt/nodejs/node-v4.6.2-linux-armv6l
and then 
> sudo ln -sf $NODEDIR/bin/node /usr/bin/node
will fail, as there is no such directory /opt/nodejs/bin/

Baud Speed --> I probably was not up to date :-) my bad !
Is there any reason to use such a low rate ? 

Thanks again !

**Comment by LowPowerLab** [comment]
Baud change explained in [this release notes/video](https://github.com/LowPowerLab/RaspberryPi-Gateway/releases/tag/v8.5).

`$NODEDIR = /opt/nodejs`
Then there are 2 links that build on each other, I didn't see anything failing:

`sudo ln -sf $NODEDIR/bin/node /usr/bin/node`
`sudo ln -sf $NODEDIR/bin/node /usr/bin/nodejs`
