### ISSUE TITLE
Gateway sometimes misses the ACKs of paired SwitchMotes 

### ISSUE THREAD

**Issue by gigawatts** [LowPowerLab/RaspberryPi-Gateway#32]
Issue: When two SwitchMote's buttons are paired / sync'ed, the ACK messages for both events (when one changes) don't always make it back to the gateway properly, thus the gateway often misses the action from one switchMote, meaning that button can't be clicked from the gateway until it receives another ACK from that button. It's possible the two ACKs are being sent so close to each other, that the gateway only picks up one instead of both, or possibly some bug in the firmware that is not sending an ACK for a remotely (meaning paired) triggered status change.

In my case, I have two switch motes setup that are sync'ed in both directions to each other. A spare button on Mote-1 turns on and off the button+relay of Mote-2. The state of the spare button on Mote-1 also gets turned on and off when Mote-2 is controlled locally.

Here is another thought along those same lines, would it be possible to add a function to the switch mote's firmware (that can be triggered from the gateway) to poll the current status of all known switches without changing their states? That way the gateway could potentially be setup to poll a remote node at a regular interval (or manually) to make sure it knows their current states, which would be a potential workaround to my issue described above.

**Comment by LowPowerLab** [comment]
IMHO this could be for other reasons than a real bug or issue.This firmware has been in use for a long time and SYNCing works very well as long as the signal path is "pretty happy". Given the small space in the electric box, the antenna often has to be curled which is not ideal but would work in most cases. Even so I would keep it as "wide open" a loop as possible. When a button is pressed, it will talk to any SYNCed SMs and also send a status to the gateway. You could try to increase the sendWithRetry retry param count to give it a better chance to SYNC.
We could continue the conversation in the forum, if a real bug is identified we can submit a report/PR here.

**Comment by gigawatts** [comment]
I finally solved this issue. See forum post here --> https://lowpowerlab.com/forum/pi-gateway/gateway-does-not-receive-both-acks-from-paired-switchmotes/msg25991/#msg25991

**Comment by LowPowerLab** [comment]
Thanks for the update!
